### ISSUE TITLE
[bot]

### ISSUE THREAD

**Issue by TheSpaceGuild** [artdude543/BeepBot-Feedback#10]
the bot don't the faces http://t.co/kf5uhE0Htj ┏(-_-)┓┏(-_-)┛┗(-_- )┓┏(-_-)┓┗(-_-)┛

**Comment by JamyDev** [comment]
Dear @TheSpaceGuild and others whom it might concern,

One hath looketh into thine issue. I am since forth able to sayeth that thine issue shall be fixed between this and a fortnight from this message reaching you.

Sorry, new information hath arisen since writing the previous part of this letter. Sir @artdude543 hath been able to fixeth thine issue and it shall be deployed soon.

Sincerely,
Sir JamyDev

**Comment by artdude543** [comment]
This should be fixed now, you will need to re-set the message for the commands affect by the bug.
